### ISSUE TITLE
No AJAX or cron?

### ISSUE THREAD

**Issue by wuffo** [PiotrCzapla/vscode-wordpress#2]
WP Site Health reports:

1. The scheduled event,  recovery_mode_clean_expired_keys, failed to run.
2. The REST API did not process the context query parameter correctly.

Every other attempt to get WP working on codespaces runs into this problem, as far as I can tell. I assume this means that AJAX and cron don't work. Is this a general port forwarding problem?

**Comment by PiotrCzapla** [comment]
Can you test on empty wordpress installation? it does seems to work for me.
![image](https://user-images.githubusercontent.com/340180/178366791-349dc285-e461-4d4e-b0d9-f7fd08f66b4d.png)

**Comment by wuffo** [comment]
Does it really work for you? The bottom 2 "improvements" mean you don't have a functioning WP installation. Everybody on codespaces gets these errors. To test this, try to schedule a post for a couple minutes from now. Likely your AJAX, mobile app/headless setup won't work either. Let me know.

**Comment by PiotrCzapla** [comment]
Thx, I see it now. I would guess it is due to the codespace domain name not being stored in the database. If so, it can be fixed with wpcli. If you are playing with this, give it a try. Here is how to change it: https://github.com/jungleboogie-pl/vscode-wordpress#workaround-for-everchanging-url

I can't have a look at the moment. But if you try it and still have the same issue, please make a screenshot from the networking tab. It will be easier to diagnose.

**Comment by wuffo** [comment]
The search-replace made 2 changes in the option_value column of the wp_options table. But, unfortunately, no change in the Site Health report. Below are screenshots from the browser's networking tab and console.

![Screenshot_20220713-142749_Kiwi Browser](https://user-images.githubusercontent.com/25521/178841228-d39b9c10-f27b-4da3-8c77-a8319e716a1f.jpg)
![Screenshot_20220713-142507_Kiwi Browser](https://user-images.githubusercontent.com/25521/178841236-c8dbf7a3-7850-4211-87d8-0b4d8a5a7097.jpg)

**Comment by PiotrCzapla** [comment]
This is very odd it looks like everything is working just fine with ajax request.  The store error looks unrelated but there is little on the network about it, so I wonder why the wp-cron is not running then.  

But as the ajax are working then the most of the things I can think of should work, and cron issue can be mitigated by calling wp-cron.php from a while loop inside of the container.  (I will add that soon) 

While you are using the container do you see any other issues with the way WordPress behaves?  It would be really helpful to see requests that are failing.  
I will dig into the store issue but I doubt it is related to corn.

**Comment by PiotrCzapla** [comment]
re> 
``` 
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://localhost/wp-admin/site-health.php' cannot be created in a document with origin
"https: //wuffo-vscode-wordpress-v47vphwqp5-80.githubpreview.dev' and URL 'https: //wuffo-vscode-wordpress-v47vphwqp5-80.githubpreview.dev/wp-admin/site-health.php
at https://wuffo-vscode-wordpress-v47vphwqp5-80.githubpreview.dev/wp-admin/site-health.php:
```
I see what is causing this error message.
The following code is being executed to get the canonical page url. It uses `HTTP_HOST`  for some reason instead of WP_SITEURL or WP_HOME
```
	$current_url  = set_url_scheme( 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] );
	$filtered_url = remove_query_arg( $removable_query_args, $current_url );
```

**Comment by PiotrCzapla** [comment]
It seems the bug about this was reported 11 years ago : ) 
[#16858](https://core.trac.wordpress.org/ticket/16858)

**Comment by PiotrCzapla** [comment]
The issue with the browser store is gone but the cron is still not working :(

**Comment by PiotrCzapla** [comment]
cron issue can be handled with 
```
while true; do wp cron event run --due-now  --quiet 2>/dev/null; done
```

But having this run every second will make debugging very hard as XDebug will connect to cron each time it runs.
So I rather add this as an additional task for the user to run manually.

With the code above the issue about actions being late disappeared.
