### ISSUE TITLE
Site Health reports "The REST API did not process the context query parameter correctly"

### ISSUE THREAD

**Issue by PiotrCzapla** [PiotrCzapla/vscode-wordpress#3]
I've created new issue to track this as the #2 should focus on wp_cron.

**Comment by PiotrCzapla** [comment]
The issue is caused by the github authorization requirements set on external URLs. Basically, the external site URL is not accessible to the curl from within the codespaces, as it needs authentication.

So this is a fake error message as most of the WordPress code that depends on the rest API calls is from the browser that is already authenticated. 

The only sane way of solving this is to set the external facing domain to be resolved to localhost, and this solves the issue.

**Comment by PiotrCzapla** [comment]
@wuffo let me know if this fixed the issues on your side.

**Comment by wuffo** [comment]
Sorry about the delay. No, I see the same 2 errors on Site Health.
One thing I noticed is that the port that opens is 80, whereas it looks like you intended for it to be 8080. I'm going to search for a plugin to run the site through a more specific set of tests to try to help isolate the problems, if any.
